@Pingo.Messages.Presentation_HostAddress = http://localhost:5018

GET {{Pingo.Messages.Presentation_HostAddress}}/api/messages/{guid}
Accept: application/json

###

PUT {{Pingo.Messages.Presentation_HostAddress}}/api/messages/{guid}
Content-Type: application/json

{
    "text": "Your message text"
}

###
