services:
    identity.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwer1234.
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        ports:
            - "8080"
            - "8081"
        volumes:
            - ${HOME}/.aspnet/dev-certs/https:/https:ro
            - ${HOME}/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets
